import 'server-only'

import { prisma } from '@/lib/db/client'
import { getAnalyticsSummary, resolveDateRange } from '@/lib/services/analytics'
import { listInventory } from '@/lib/services/inventory'

/**
 * Every "insight" here is computed directly from the database — nothing is
 * generated by a language model, and nothing is invented. When there isn't
 * enough data to answer meaningfully, the function says so explicitly
 * instead of guessing. This is intentionally a fixed set of backend tools
 * rather than free-form chat; wiring up a real LLM later means adding
 * function-calling on top of these same tools, not replacing them.
 */

export type AssistantAnswer = {
  question: string
  answer: string
}

export async function answerTopProducts(organizationId: string): Promise<AssistantAnswer> {
  const range = resolveDateRange('30d')
  const summary = await getAnalyticsSummary(organizationId, range)

  if (summary.topProducts.length === 0) {
    return {
      question: 'Какие товары продаются лучше всего?',
      answer: 'Пока недостаточно данных. Завершите несколько заказов, чтобы увидеть лидеров продаж.',
    }
  }

  const lines = summary.topProducts
    .slice(0, 5)
    .map((p, i) => `${i + 1}. ${p.name} — ${p.units} шт., выручка ${p.revenue.toFixed(2)}`)

  return {
    question: 'Какие товары продаются лучше всего?',
    answer: `За последние 30 дней:\n${lines.join('\n')}`,
  }
}

export async function answerLowStock(organizationId: string): Promise<AssistantAnswer> {
  const rows = await listInventory(organizationId)
  const low = rows.filter((r) => r.health !== 'IN_STOCK')

  if (low.length === 0) {
    return {
      question: 'Какие товары скоро закончатся?',
      answer: 'Сейчас нет товаров с низким запасом.',
    }
  }

  const lines = low
    .slice(0, 10)
    .map((r) => {
      const forecast =
        r.daysRemaining !== null
          ? `осталось примерно ${r.daysRemaining.toFixed(1)} дн.`
          : 'недостаточно данных для прогноза'
      return `- ${r.product.name}: осталось ${r.physicalStock} (${forecast})`
    })

  return {
    question: 'Какие товары скоро закончатся?',
    answer: lines.join('\n'),
  }
}

export async function answerHighViewsLowConversion(
  organizationId: string
): Promise<AssistantAnswer> {
  const listings = await prisma.listing.findMany({
    where: { organizationId, status: 'ACTIVE' },
    include: { product: true },
  })

  const withViewData = listings.filter((l) => l.views !== null)

  if (withViewData.length === 0) {
    return {
      question: 'Какие объявления на OLX имеют много просмотров, но мало продаж?',
      answer: 'Пока недостаточно данных. Подключите OLX и синхронизируйте объявления, чтобы увидеть статистику просмотров.',
    }
  }

  const flagged = withViewData.filter(
    (l) => (l.views ?? 0) > 100 && (l.messagesCount ?? 0) < 5
  )

  if (flagged.length === 0) {
    return {
      question: 'Какие объявления на OLX имеют много просмотров, но мало продаж?',
      answer: 'Сейчас нет объявлений с таким сочетанием: много просмотров и мало обращений.',
    }
  }

  const lines = flagged.map(
    (l) =>
      `- ${l.product.name}: ${l.views} просмотров, ${l.messagesCount ?? 0} сообщений. Стоит пересмотреть цену или качество объявления.`
  )

  return {
    question: 'Какие объявления на OLX имеют много просмотров, но мало продаж?',
    answer: lines.join('\n'),
  }
}

export async function answerRevenue(organizationId: string): Promise<AssistantAnswer> {
  const range = resolveDateRange('30d')
  const summary = await getAnalyticsSummary(organizationId, range)

  if (!summary.hasAnyData) {
    return {
      question: 'Какая была выручка за последние 30 дней?',
      answer: 'Пока недостаточно данных. За последние 30 дней нет завершённых заказов.',
    }
  }

  return {
    question: 'Какая была выручка за последние 30 дней?',
    answer: `Выручка: ${summary.revenue.toFixed(2)}, прибыль: ${summary.profit.toFixed(2)}, по ${summary.orderCount} заказам (маржа ${summary.margin.toFixed(1)}%).`,
  }
}

export async function answerLowMarginProducts(
  organizationId: string
): Promise<AssistantAnswer> {
  const products = await prisma.product.findMany({
    where: { organizationId, status: 'ACTIVE' },
  })

  const withMargin = products
    .map((p) => {
      const selling = Number(p.sellingPrice)
      const purchase = Number(p.purchasePrice)
      const margin = selling > 0 ? ((selling - purchase) / selling) * 100 : 0
      return { name: p.name, sku: p.sku, margin }
    })
    .filter((p) => p.margin < 15)
    .sort((a, b) => a.margin - b.margin)

  if (withMargin.length === 0) {
    return {
      question: 'Какие товары имеют низкую маржу?',
      answer:
        products.length === 0
          ? 'Пока недостаточно данных. Добавьте товары, чтобы увидеть анализ маржи.'
          : 'Сейчас нет товаров с маржой ниже 15%.',
    }
  }

  const lines = withMargin
    .slice(0, 10)
    .map((p) => `- ${p.name} (${p.sku}): маржа ${p.margin.toFixed(1)}%`)

  return {
    question: 'Какие товары имеют низкую маржу?',
    answer: lines.join('\n'),
  }
}

export const ASSISTANT_QUESTIONS = [
  { id: 'top-products', label: 'Какие товары продаются лучше всего?' },
  { id: 'low-stock', label: 'Какие товары скоро закончатся?' },
  { id: 'views-conversion', label: 'Какие объявления на OLX имеют много просмотров, но мало продаж?' },
  { id: 'revenue', label: 'Какая была выручка за последние 30 дней?' },
  { id: 'low-margin', label: 'Показать товары с низкой маржой.' },
] as const

export async function answerQuestion(
  organizationId: string,
  questionId: string
): Promise<AssistantAnswer> {
  switch (questionId) {
    case 'top-products':
      return answerTopProducts(organizationId)
    case 'low-stock':
      return answerLowStock(organizationId)
    case 'views-conversion':
      return answerHighViewsLowConversion(organizationId)
    case 'revenue':
      return answerRevenue(organizationId)
    case 'low-margin':
      return answerLowMarginProducts(organizationId)
    default:
      return { question: 'Неизвестный вопрос', answer: 'Сейчас я могу отвечать только на перечисленные вопросы.' }
  }
}
